


Assignment No1. Implement 50 methods of Numpy


In [1]:
import numpy as np
var1 = np.array(range(5)) #1st Method
var1


array([0, 1, 2, 3, 4])

In [2]:
var2 = np.zeros(4)        #2nd Method
print(var2)
var2 = np.zeros((2,3,4)) # zeros(Dimentions , row , column)
var2

[0. 0. 0. 0.]


array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [3]:
var3 = np.ones(5)          #3rd Method
print(var3)
var3 = np.ones(5 , dtype=np.int)
print(var3)
var3 = np.ones(5 , dtype=np.bool)
print(var3)
var3 = np.ones(5 , dtype=np.str)
var3

[1. 1. 1. 1. 1.]
[1 1 1 1 1]
[ True  True  True  True  True]


array(['1', '1', '1', '1', '1'], dtype='<U1')

In [4]:
var4 = np.arange(7)         #4th Method
print(var4)
var4 = np.arange(0,11,2) #arange(StartingPoint , Endingpoint_Excluded , Increament)
var4

[0 1 2 3 4 5 6]


array([ 0,  2,  4,  6,  8, 10])

In [5]:
var5 = np.empty(5)           #5th Method
var5 #it will returns the random value from the memory

array([5.e-324, 5.e-324, 5.e-324, 5.e-324, 5.e-324])

In [6]:
var6 = np.linspace(0,11,5)   #6th Method
#linspace(StartingPoint , Ending_Point_Included , Total_number Or specific Interval Points)
var6

array([ 0.  ,  2.75,  5.5 ,  8.25, 11.  ])

In [7]:
var7 = np.arange(3*4*4).reshape(3,4,4) #7th Method
var7

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]]])

In [9]:
var7.shape #8th Method

(3, 4, 4)

In [10]:
var7.ndim #9th Method

3

In [11]:
var7.dtype #10th Method

dtype('int64')

In [12]:
var7.dtype.name  #11th Method

'int64'

In [14]:
var7.itemsize   #12th Method>>>>>Length of one array element in bytes.

8

In [15]:
var7.size    #13 Method Size of array

48

In [16]:
type(var7)    #14 Method


numpy.ndarray

In [17]:
var8 = np.array([9,8,6,3,5,2,7,4,1])
print(np.sort(var8))            #15th Method>> Sorting the whole array

[1 2 3 4 5 6 7 8 9]


In [18]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
print(np.concatenate((a,b)))    # 16th Method Concatenatoins

[1 2 3 4 5 6 7 8]


In [19]:
var9 = np.array([1,2,3,4,5,6,7])
var9 = var9[np.newaxis,:]        #  17th Method
print(var9)
var9.shape

[[1 2 3 4 5 6 7]]


(1, 7)

In [20]:
var9 = np.array([1,2,3,4,5,6,7])  #18
var9 = var9[:,np.newaxis]
print(var9)
var9.shape

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]


(7, 1)

In [21]:
a = np.array([1,2,3,4,5,6,7,8,9])
var10 = np.expand_dims(a , axis=1)#19 Method>>>>Second method Used for expending the dimention on Y-axis
print(var10.shape)
var10

(9, 1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [22]:
a = np.array([1,2,3,4,5,6,7,8,9])
var10 = np.expand_dims(a , axis=0)#19 Method>>>>Second method Used for expending the dimention on X-axis
print(var10.shape)
var10

(1, 9)


array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [23]:
a = np.array([0,1,2,3,4,5,6,7,8,9])
var11 = a[np.nonzero(a)]          #20th Method>>>>>>>It will return all non zero elements 
var11

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a = np.array([[0,1,2,3,4],[34,664,23,5,4],[13,68,8,4,2]])
var11 = np.nonzero(a<5)           #21th Method>>>>>>>It will return all non zero elements 
var11

(array([0, 0, 0, 0, 0, 1, 2, 2]), array([0, 1, 2, 3, 4, 4, 3, 4]))

In [26]:
a1 = np.array([[1, 1],     #22 Method>>>>>>> it will Stack arrays vertically
               [2, 2]])
a2 = np.array([[3, 3],
         [4, 4]])
var12 = np.vstack((a1,a2))   
var12

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [27]:

a1 = np.array([[1, 1],    #23 Method>>>>>>> it will Stack arrays Horizentally
               [2, 2]])
a2 = np.array([[3, 3],
         [4, 4]])
var12 = np.hstack((a1,a2))       
var12

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [28]:
a = np.arange(1,25).reshape(2,12)
var13 = np.hsplit(a,3)  #24 Method>>>>>>> This method splits into many features
var13

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [29]:

rng = np.random.default_rng(1)  #25 Method>>>>>>>> This method will set the defualt value
var14 = rng.random(3)           #26 Method>>>>>>>> This method will generate 3 ramdom numbers
var14

array([0.51182162, 0.9504637 , 0.14415961])

In [30]:
VAR15 = rng.integers(7, size=(2, 4)) #27 Method >>>>>> Used to genrate integer Random numbers
VAR15

array([[5, 6, 1, 2],
       [6, 2, 1, 5]])

In [31]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
var16 = np.unique(a)            #28 Method will distinct the values
var16

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [32]:
arr = np.arange(6).reshape((2, 3))
var17 = arr.transpose()          #29 it will reverse the axises
var17

array([[0, 3],
       [1, 4],
       [2, 5]])

In [33]:
var18 = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
var18.sum()      #30 Method

216

In [34]:
var18 = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
var18.min()       #31 Method

11

In [35]:
var18 = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
var18.max()         #32 Method

20

In [36]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
var19 = np.flip(a)                #33 Method
var19

array([20, 19, 18, 14, 11, 13, 12, 17, 16, 15, 14, 13, 12, 11, 11])

In [37]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
var20 = x.flatten() #34 Method,  When you use flatten, changes to your new array won’t change the parent array.
var20[0] = 99
print(x)
var20

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
var20 = x.ravel()                #35 Method,when you use ravel, the changes you make to the new array will affect the parent array.
var20[0] = 99
print(x)
var20

[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [39]:
a = np.array([1,2,3])
np.r_[np.repeat(a, 3), np.tile(a, 3)] #36

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [40]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
var21 = np.intersect1d(a,b)           #37 Method Intersactoin Between 2 Points
var21

array([2, 4])

In [41]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
var22 = np.setdiff1d(a,b)  #38 Method 
var22

array([1, 2, 3, 4])

In [42]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
var23 = np.where(a==b)             #39 Method Get possition where both have same elements
var23

(array([1, 3, 5, 7]),)

In [43]:
a = np.array([1,2,3,2,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9])
var24 = np.column_stack((a,b))     #40 Method convert Rows into column
var24

array([[ 1,  7],
       [ 2,  2],
       [ 3, 10],
       [ 2,  2],
       [ 4,  7],
       [ 3,  4],
       [ 4,  9],
       [ 5,  4],
       [ 6,  9]])

In [44]:
var25=np.all([[True,False],[True,True]]) #41 Method
var25

False

In [45]:
var26=np.any([[True, False], [True, True]]) #42 Method
var26

True

In [46]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8]) 
var26 = np.multiply(a,b)                    #43 Method
var26

array([ 7,  4, 30,  4, 21, 16, 27, 16, 45, 48])

In [47]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
var26 = np.divide(a,b)                      #44 Method
var26


array([0.14285714, 1.        , 0.3       , 1.        , 0.42857143,
       1.        , 0.33333333, 1.        , 0.55555556, 0.75      ])

In [48]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
var26 = np.subtract(a,b)                    #45 Method
var26

array([-6,  0, -7,  0, -4,  0, -6,  0, -4, -2])

In [49]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
var26 = np.add(a,b)                        #46 Method
var26

array([ 8,  4, 13,  4, 10,  8, 12,  8, 14, 14])

In [50]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
var26 = np.exp(a)                       #47 Method
var26

array([  2.71828183,   7.3890561 ,  20.08553692,   7.3890561 ,
        20.08553692,  54.59815003,  20.08553692,  54.59815003,
       148.4131591 , 403.42879349])

In [51]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
var26 = np.sqrt(b)                      #48 Method
var26

array([2.64575131, 1.41421356, 3.16227766, 1.41421356, 2.64575131,
       2.        , 3.        , 2.        , 3.        , 2.82842712])

In [52]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
var27 = np.split(a,3)                   #49 Method ,Split array into 3 sub arrays
var27

[array([11, 11, 12, 13, 14]),
 array([15, 16, 17, 12, 13]),
 array([11, 14, 18, 19, 20])]

In [53]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
var28 = np.delete(a , 1)                #50  Method Delete Element from the array (Array , index)
var28

array([11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [54]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
var28 = np.insert(a , 4 ,555)   #50 Method Delete Element from the array (Array , index , value)
var28

array([ 11,  11,  12,  13, 555,  14,  15,  16,  17,  12,  13,  11,  14,
        18,  19,  20])